modify travis

diff --git a/travis/run_on_pull_requests b/travis/run_on_pull_requests
--- a/travis/run_on_pull_requests
+++ b/travis/run_on_pull_requests
@@ -1,15 +1,19 @@
 #!/bin/bash
 
+# goimports test
 diff <(goimports -d $(find . -type f -name '*.go' -not -path "*/vendor/*")) <(printf "")
 
 if [ $? -ne 0 ]; then
-  echo "goimports format error" >&2
-  exit 1
+echo "goimports format error" >&2
+exit 1
 fi
 
-go test -p 1 ./...
+# run go test
+go test -v -mod=vendor ./...
 
 if [ $? -ne 0 ]; then
-  echo "go test fail" >&2
-  exit 1
+echo "go test fail" >&2
+exit 1
 fi
+
+exit 0
